# Generated by `cargo run -p setools-xtask -- generate`; do not edit.
complete -c sechecker -s h -l help -f -d 'show this help message and exit'
complete -c sechecker -l version -f -d 'show program\'s version number and exit'
complete -c sechecker -s o -l output_file -r -F -d 'Path to log output.'
complete -c sechecker -s v -l verbose -f -d 'Print extra informational messages'
complete -c sechecker -l debug -f -d 'Enable debugging.'
complete -c sechecker -l json -f -d 'Emit command-specific versioned JSON output.'
