[package]
name = "setools-checker"
description = "Configuration-driven SELinux policy checks for SETools-compatible tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license = "LGPL-2.1-only"
publish = false

[dependencies]
setools-policy = { path = "../setools-policy" }
setools-query = { path = "../setools-query" }

[lints]
workspace = true
