[package]
name = "setools-policy-binary-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
setools-policy-binary = { path = "../crates/setools-policy-binary" }

[[bin]]
name = "parse_policy"
path = "fuzz_targets/parse_policy.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
